spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=${KEY_STORE_PATH:classpath:llamademo.p12}
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${KEY_STORE_PASSWORD}
server.ssl.key-alias=${KEY_ALIAS:llamademo}

