spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:llamademo.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=mexico00
server.ssl.key-alias=llamademo

